apiVersion: v1
kind: Service
metadata:
  name: hello-nam
  labels:
    app: hello-nam
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-nam
    tier: hello-nam
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nam
  labels:
    app: hello-nam
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-nam
        tier: hello-nam
    spec:
      containers:
      - image: 10.9.2.151:5000/hello-nam:0e04a0b
        name: hello-nam
        ports:
        - containerPort: 80
          name: hello-nam